### ISSUE TITLE
default.css ignores <ol>

### ISSUE THREAD

**Issue by aronwc** [egonSchiele/mdpress#27]
[default.css](../blob/master/lib/impress_css/default.css) has a rule:

``` css
li {
    line-height: 50px;
    list-style: disc;
}
```

But this makes `ol` elements appear with bullets instead of numbers. Perhaps this instead?

``` css
ul>li {
    line-height: 50px;
    list-style: disc;
}

ol>li {
    line-height: 50px;
    list-style: decimal;
}
```

Or, more simply, remove the list-style attribute?

``` css
li {
    line-height: 50px;
}
```

Thanks for a great package!
